"""The demo tools and their sync: ``plans/demo_code_mcp.md``.

Offline throughout.  The demo repo is a real git repository made in
``tmp_path`` and served to the sync as a ``file://`` remote, so the git
commands the portal runs on Render run here too -- only the network is
missing.  Tool calls go through the WSGI mount, as in ``test_course_mcp.py``.
"""

from __future__ import annotations

import json
import os
import subprocess
import threading
import time
from pathlib import Path

import pytest

import llmgrader.coursemcp.code as code_module
from test_course_mcp import build_app, call_tool, rpc, tool_items, within

# demos/scalar_fun/scalar_fun_vitis/src/scalar_fun.cpp in hwdesign, verbatim:
# the AXI4-Lite pragmas are lines 12-16.
SCALAR_FUN_CPP = """#include "scalar_fun.h"

// A single artificial neuron:  y = max(w*x + b, 0).
//
// Every argument, and the function's own start/done handshake (`return`),
// is bound to the same AXI4-Lite bundle.  Vitis HLS turns that bundle into
// the register map the processor reads and writes:  the processor writes
// x, w and b into their registers, sets ap_start, polls ap_done, then
// reads y back out.
void simp_fun(int x, int w, int b, int& y) {

    #pragma HLS INTERFACE s_axilite port=x      bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=w      bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=b      bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=y      bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=return bundle=CTRL

    int act_in = w * x + b;
    if (act_in > 0)
        y = act_in;
    else
        y = 0;
}
"""

PROCIF_INDEX = """---
title: Bus Basics and Memory-Mapped Interfaces
parent: Demos
nav_order: 4
has_children: true
---

# Bus Basics and Memory-Mapped Interfaces

In this unit we build an IP with an AXI4-Lite register interface.

The files are in `hwdesign/demos/scalar_fun/scalar_fun_vitis`.
"""

PROCIF_VITIS = """---
title: Building the Vitis IP
parent: Bus Basics and Memory-Mapped Interfaces
nav_order: 1
---

# Building the Vitis IP

## Interface pragmas

Each argument gets an s_axilite pragma:

~~~c
#pragma HLS INTERFACE s_axilite port=x bundle=CTRL
~~~

The old version was in `hwdesign/demos/basic_logic/old_fun.sv`.
"""

STREAM_INDEX = """---
title: AXI4-Streaming
nav_order: 5
---

# AXI4-Stream Interface

In the [scalar function example](../procif/), the IP used registers.
Everything is in `hwdesign/demos/stream/avgfilt`.
"""

FIFOIF_INDEX = """---
title: FIFO interfaces
nav_order: 6
---

# FIFO interfaces

The code is in [the poly demo](https://github.com/test/hwdesign/tree/main/demos/stream/poly).
"""

NOTEBOOK = {
    "cells": [
        {"cell_type": "markdown", "source": ["# Driving the IP\n"]},
        {"cell_type": "code", "source": ["ol = Overlay('scalar_fun.bit')\n"],
         "outputs": [{"output_type": "stream", "text": ["OUTPUT_ONLY_TOKEN\n"]}]},
    ],
    "metadata": {}, "nbformat": 4, "nbformat_minor": 5,
}

REPO_FILES = {
    "demos/scalar_fun/scalar_fun_vitis/src/scalar_fun.cpp": SCALAR_FUN_CPP,
    "demos/scalar_fun/scalar_fun_vitis/hls_component/syn/simp_fun.cpp": "// s_axilite generated\n",
    "demos/scalar_fun/overlay/design.tcl": "#****\n# Generated by Vivado on Mon\n# s_axilite\n",
    "demos/scalar_fun/notebooks/run.ipynb": json.dumps(NOTEBOOK),
    "demos/fsm/counter.sv": "module counter;\n  always_ff @(posedge clk) q <= d;\nendmodule\n",
    "demos/fsm/long.py": "".join(f"x{n} = {n}\n" for n in range(1, 501)),
    "demos/stream/avgfilt/avgfilt.cpp": "// moving average\n",
    "demos/stream/poly/poly.cpp": "// polynomial\n",
    "docs/demos/index.md": "---\ntitle: Demos\n---\n\n# Demos\n",
    "docs/demos/procif/index.md": PROCIF_INDEX,
    "docs/demos/procif/vitis_ip.md": PROCIF_VITIS,
    "docs/demos/stream/index.md": STREAM_INDEX,
    "docs/demos/fifoif/index.md": FIFOIF_INDEX,
    "_config.yml": 'url: "https://example.github.io"\nbaseurl: "/hwdesign"\n',
    "units/unit04/slides.txt": "not an include\n",
}
REPO_BINARIES = {
    "demos/scalar_fun/overlay/design.bit": b"\x00\x01binary s_axilite\x00",
    "docs/demos/procif/images/fig.png": b"\x89PNG\x00",
}

CODE_CONFIG = {
    "repo": "https://github.com/test/hwdesign", "branch": "main",
    "includes": [{"path": "demos", "kind": "code"}, {"path": "docs/demos", "kind": "doc"}],
    "excludes": [], "site": None, "links": None,
}

DECKS = {
    "procif": ("Unit 4:  Memory and Processor Interfaces",
               {50: {"text": "See demos/scalar_fun/scalar_fun_vitis on the course site"}}),
    "fsm": ("Unit 2:  Sequential Logic and FSMs",
            {35: {"text": "Run the demo", "links": ["https://example.github.io/hwdesign/docs/demos/stream/"]}}),
}


def git(*args, cwd) -> str:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True,
                          text=True).stdout


def commit_all(repo: Path, message: str = "update") -> str:
    git("add", "-A", cwd=repo)
    git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", message, cwd=repo)
    return git("rev-parse", "HEAD", cwd=repo).strip()


def make_repo(root: Path) -> Path:
    repo = root / "hwdesign"
    for path, text in REPO_FILES.items():
        (repo / path).parent.mkdir(parents=True, exist_ok=True)
        (repo / path).write_text(text, encoding="utf-8")
    for path, data in REPO_BINARIES.items():
        (repo / path).parent.mkdir(parents=True, exist_ok=True)
        (repo / path).write_bytes(data)
    git("init", "-q", "-b", "main", cwd=repo)
    git("config", "uploadpack.allowFilter", "true", cwd=repo)
    commit_all(repo, "demos")
    return repo


def write_materials(package: Path, code: dict | None = CODE_CONFIG) -> None:
    """A course package's MCP material: two decks and, optionally, <code>."""
    root = package / "mcp_materials"
    manifest = {"version": 1, "decks": [], "units": [], "unit_types": []}
    for deck_id, (unit, slides) in DECKS.items():
        count = max(slides)
        deck_dir = root / "slides" / deck_id
        deck_dir.mkdir(parents=True)
        entries = []
        for n in range(1, count + 1):
            spec = slides.get(n, {})
            entries.append({"n": n, "title": f"{deck_id} {n}", "text": spec.get("text", ""),
                            "notes": "", "image": None, "description": "",
                            "links": spec.get("links", [])})
        (deck_dir / "deck.json").write_text(json.dumps(
            {"id": deck_id, "unit": unit, "title": deck_id, "slides": entries}), encoding="utf-8")
        manifest["decks"].append({"id": deck_id, "unit": unit, "title": deck_id,
                                  "slides": count, "images": False, "warning": ""})
    if code is not None:
        manifest["code"] = code
    (root / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")


def make_app(tmp_path, monkeypatch, *, code_switch: bool = True, repo: Path | None = None):
    if code_switch:
        monkeypatch.setenv("LLMGRADER_MCP_CODE", "1")
    else:
        monkeypatch.delenv("LLMGRADER_MCP_CODE", raising=False)
    monkeypatch.delenv("LLMGRADER_CODE_SYNC_TTL_S", raising=False)
    repo = repo or make_repo(tmp_path)
    monkeypatch.setattr(code_module, "remote_url", lambda config: repo.as_uri())
    app = build_app(tmp_path, monkeypatch, enabled=True)
    storage = tmp_path / "storage" / "courses"
    write_materials(storage / "alpha" / "soln_pkg")
    write_materials(storage / "beta" / "soln_pkg", code=None)
    return app


@pytest.fixture()
def app(tmp_path, monkeypatch):
    return make_app(tmp_path, monkeypatch)


@pytest.fixture()
def client(app):
    return app.test_client()


def payload(result: dict):
    assert not result.get("isError"), result
    return json.loads(result["content"][0]["text"])


def error_text(result: dict) -> str:
    assert result.get("isError"), result
    return result["content"][0]["text"]


def search(client, query, **kwargs):
    return payload(call_tool(client, "search_demos", {"course_id": "alpha", "query": query, **kwargs}))


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


def test_search_finds_the_axilite_pragmas_as_one_hit(client) -> None:
    result = search(client, "s_axilite")
    code_hits = [h for h in result["hits"] if h["kind"] == "code"]
    assert len(code_hits) == 1, result
    hit = code_hits[0]
    assert hit["path"] == "demos/scalar_fun/scalar_fun_vitis/src/scalar_fun.cpp"
    assert (hit["start_line"], hit["end_line"]) == (12, 16)
    assert hit["demos"] == ["procif"]
    assert hit["language"] == "hls-cpp"
    commit = client.application.course_mcp.code.sync_for("alpha").snapshot.commit
    assert hit["source_url"] == (
        f"https://github.com/test/hwdesign/blob/{commit}/"
        "demos/scalar_fun/scalar_fun_vitis/src/scalar_fun.cpp#L12-L16")
    assert "> 12" in hit["context"] and "  10" in hit["context"]


def test_docs_hits_come_first_with_the_published_page(client) -> None:
    hits = search(client, "s_axilite")["hits"]
    assert hits[0]["kind"] == "doc"
    assert hits[0]["path"] == "docs/demos/procif/vitis_ip.md"
    assert hits[0]["heading"] == "Interface pragmas"
    assert hits[0]["view_url"] == ("https://example.github.io/hwdesign/docs/demos/procif/"
                                   "vitis_ip#interface-pragmas")
    assert "?plain=1#L" in hits[0]["source_url"]


def test_search_is_case_and_space_insensitive_and_can_be_scoped(client) -> None:
    upper = search(client, "S_AXILITE")
    assert [h["path"] for h in upper["hits"]] == [h["path"] for h in search(client, "s_axilite")["hits"]]
    assert search(client, "pragma HLS   INTERFACE  s_axilite")["hits_shown"] >= 1
    assert search(client, "s_axilite", demo="fsm")["hits"] == []
    assert all(h["kind"] == "doc" for h in search(client, "s_axilite", kind="doc")["hits"])


@pytest.mark.parametrize("path", [
    "../../../etc/passwd",
    "..\\..\\windows\\win.ini",
    "/etc/passwd",
    "C:/Windows/win.ini",
    "demos/scalar_fun/../../units/unit04/slides.txt",
    "units/unit04/slides.txt",
    "_config.yml",
])
def test_paths_outside_the_includes_are_refused(client, path) -> None:
    result = call_tool(client, "get_demo_file", {"course_id": "alpha", "path": path})
    assert result.get("isError"), result


def test_build_output_binaries_and_generated_tcl_are_not_served(client) -> None:
    files = [f["path"] for f in tool_items(call_tool(
        client, "list_demo_files", {"course_id": "alpha", "demo": "procif"}))]
    assert "demos/scalar_fun/scalar_fun_vitis/src/scalar_fun.cpp" in files
    for hidden in ("demos/scalar_fun/overlay/design.bit", "demos/scalar_fun/overlay/design.tcl",
                   "demos/scalar_fun/scalar_fun_vitis/hls_component/syn/simp_fun.cpp",
                   "docs/demos/procif/images/fig.png"):
        assert hidden not in files
        text = error_text(call_tool(client, "get_demo_file", {"course_id": "alpha", "path": hidden}))
        assert "not served" in text or "No file" in text
    assert not any("overlay" in h["path"] or "hls_component" in h["path"]
                   for h in search(client, "s_axilite")["hits"])


def test_notebooks_are_served_without_their_outputs(client) -> None:
    assert search(client, "OUTPUT_ONLY_TOKEN")["hits"] == []
    [hit] = search(client, "Overlay('scalar_fun.bit')")["hits"]
    assert hit["language"] == "notebook"
    assert "#L" not in hit["source_url"]     # GitHub renders notebooks: no line anchors


def test_a_docs_page_reads_without_front_matter_and_lists_what_it_cites(client) -> None:
    page = payload(call_tool(client, "get_demo_file",
                             {"course_id": "alpha", "path": "docs/demos/procif/index.md"}))
    assert page["title"] == "Bus Basics and Memory-Mapped Interfaces"
    assert page["first_line"] == 7 and page["start_line"] == 7
    assert "nav_order" not in page["text"]
    assert page["cites"] == ["demos/scalar_fun/scalar_fun_vitis"]
    assert page["view_url"] == "https://example.github.io/hwdesign/docs/demos/procif/"


def test_reading_is_windowed(client) -> None:
    def read(**kw):
        return payload(call_tool(client, "get_demo_file",
                                 {"course_id": "alpha", "path": "demos/fsm/long.py", **kw}))
    first = read()
    assert (first["start_line"], first["end_line"], first["truncated"]) == (1, 400, True)
    rest = read(start_line=401)
    assert (rest["start_line"], rest["end_line"], rest["truncated"]) == (401, 500, False)
    assert read(start_line=10, end_line=12)["text"].splitlines()[0].strip() == "10  x10 = 10"
    assert "has lines" in error_text(call_tool(client, "get_demo_file", {
        "course_id": "alpha", "path": "demos/fsm/long.py", "start_line": 900}))
    # The docs write paths with the repo's name in front.
    assert payload(call_tool(client, "get_demo_file", {
        "course_id": "alpha", "path": "hwdesign/demos/fsm/counter.sv"}))["path"] == "demos/fsm/counter.sv"


def test_list_demos_derives_the_demos_and_their_links(client) -> None:
    demos = {d["demo"]: d for d in tool_items(call_tool(client, "list_demos", {"course_id": "alpha"}))}
    assert set(demos) == {"procif", "stream", "fifoif", "fsm"}
    procif = demos["procif"]
    assert procif["title"] == "Bus Basics and Memory-Mapped Interfaces"
    assert procif["description"].startswith("In this unit we build an IP")
    assert procif["code"] == ["demos/scalar_fun/scalar_fun_vitis"]
    assert procif["slides"][0]["deck"] == "procif" and procif["slides"][0]["slide"] == 50
    assert procif["units"][0]["unit"] == "Unit 4:  Memory and Processor Interfaces"
    assert "procif:50" in procif["units"][0]["via"]
    assert [p["path"] for p in procif["docs"]] == ["docs/demos/procif/index.md",
                                                   "docs/demos/procif/vitis_ip.md"]
    # A folder holding two demos is neither's code; each keeps its own part.
    assert demos["stream"]["code"] == ["demos/stream/avgfilt"]
    assert demos["fifoif"]["code"] == ["demos/stream/poly"]
    assert demos["stream"]["related"] == ["procif"]
    # A slide hyperlink to a docs page links that demo.
    assert {(s["deck"], s["slide"]) for s in demos["stream"]["slides"]} == {("fsm", 35)}
    # Code no docs page cites is a demo of its own, and a deck of its name gives its unit.
    assert demos["fsm"]["code"] == ["demos/fsm"]
    assert demos["fsm"]["units"][0]["unit"].startswith("Unit 2")
    only_unit4 = tool_items(call_tool(client, "list_demos", {"course_id": "alpha", "unit": "unit 4"}))
    assert [d["demo"] for d in only_unit4] == ["procif"]


def test_slides_say_which_demos_they_cite(client) -> None:
    # A slide tool never waits for the demos, so there must be a copy first.
    first = json.loads(call_tool(client, "get_slide", {"course_id": "alpha", "deck": "procif",
                                                        "slide": 50})["content"][0]["text"])
    tool_items(call_tool(client, "list_demos", {"course_id": "alpha"}))
    result = call_tool(client, "get_slide", {"course_id": "alpha", "deck": "procif", "slide": 50})
    slide = json.loads(result["content"][0]["text"])
    assert slide["demos"] == [{"demo": "procif", "title": "Bus Basics and Memory-Mapped Interfaces"}]
    plain = json.loads(call_tool(client, "get_slide", {"course_id": "alpha", "deck": "procif",
                                                        "slide": 1})["content"][0]["text"])
    assert "demos" not in plain


def test_errors_are_readable(client) -> None:
    assert "Unknown course" in error_text(call_tool(client, "list_demos", {"course_id": "nope"}))
    assert "has not published demos" in error_text(call_tool(client, "list_demos", {"course_id": "beta"}))
    text = error_text(call_tool(client, "list_demo_files", {"course_id": "alpha", "demo": "nope"}))
    assert "Valid demos" in text and "'procif'" in text
    assert "kind must be" in error_text(call_tool(client, "search_demos", {
        "course_id": "alpha", "query": "x", "kind": "binary"}))
    assert "empty" in error_text(call_tool(client, "search_demos", {"course_id": "alpha", "query": " "}))


def test_list_courses_carries_the_code_version(client) -> None:
    call_tool(client, "list_demos", {"course_id": "alpha"})
    courses = {c["course_id"]: c for c in tool_items(call_tool(client, "list_courses"))}
    commit = client.application.course_mcp.code.sync_for("alpha").snapshot.commit
    assert courses["alpha"]["code_version"] == commit[:12]
    assert "code_version" not in courses["beta"]


def test_demo_tools_are_off_without_the_switch(tmp_path, monkeypatch) -> None:
    client = make_app(tmp_path, monkeypatch, code_switch=False).test_client()
    names = {t["name"] for t in rpc(client, "tools/list").get_json()["result"]["tools"]}
    assert "search_demos" not in names
    assert "get_slide" in names
    assert not (tmp_path / "storage" / "courses" / "alpha" / "code").exists()


# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------


def test_every_demo_tool_argument_is_classified(client) -> None:
    from llmgrader.coursemcp.usage import IDENTIFIER_ARGUMENTS, REDACTED_ARGUMENTS

    tools = rpc(client, "tools/list").get_json()["result"]["tools"]
    assert {"list_demos", "list_demo_files", "get_demo_file", "search_demos"} <= {t["name"] for t in tools}
    unlisted = {(t["name"], arg) for t in tools for arg in t["inputSchema"].get("properties", {})
                if arg not in IDENTIFIER_ARGUMENTS | REDACTED_ARGUMENTS}
    assert unlisted == set()


def test_usage_rows_record_demo_and_file_but_not_the_query(app, client) -> None:
    import sqlite3

    # A row is written as the response closes, so the client must buffer it.
    for name, args in [("search_demos", {"query": "s_axilite"}),
                       ("get_demo_file", {"path": "hwdesign/demos/fsm/counter.sv"})]:
        response = rpc(client, "tools/call", {"name": name,
                                              "arguments": {"course_id": "alpha", **args}},
                       buffered=True)
        assert response.status_code == 200
    db = app.course_mcp.usage.db_path
    with sqlite3.connect(db) as conn:
        conn.row_factory = sqlite3.Row
        rows = {r["tool"]: dict(r) for r in conn.execute(
            "SELECT * FROM mcp_calls WHERE tool IN ('search_demos', 'get_demo_file')")}
    commit = app.course_mcp.code.sync_for("alpha").snapshot.commit
    assert json.loads(rows["search_demos"]["args_json"])["query"] == "<redacted>"
    assert "s_axilite" not in json.dumps(rows["search_demos"])
    assert rows["search_demos"]["result_items"] >= 2
    assert rows["get_demo_file"]["path"] == "demos/fsm/counter.sv"
    assert rows["get_demo_file"]["demo"] == "fsm"
    assert rows["get_demo_file"]["code_version"] == commit[:12]


# ---------------------------------------------------------------------------
# Sync
# ---------------------------------------------------------------------------


def library(app):
    return app.course_mcp.code


def test_nothing_is_fetched_until_the_first_mcp_request(tmp_path, monkeypatch) -> None:
    app = make_app(tmp_path, monkeypatch)
    code_dir = tmp_path / "storage" / "courses" / "alpha" / "code"
    assert not code_dir.exists()
    rpc(app.test_client(), "tools/list")
    sync = library(app).sync_for("alpha")
    sync._thread.join(30)
    assert (code_dir / "mirror" / ".git").is_dir()
    assert sync.snapshot is not None


def blocking_git(monkeypatch, release: threading.Event, calls: list):
    """run_git that hangs on any network command until *release* is set."""
    real = code_module.run_git

    def run(args, **kwargs):
        calls.append(args[0])
        if args[0] in ("clone", "ls-remote", "fetch"):
            release.wait(30)
        return real(args, **kwargs)

    monkeypatch.setattr(code_module, "run_git", run)


def test_first_fetch_waits_briefly_then_says_so(tmp_path, monkeypatch) -> None:
    app = make_app(tmp_path, monkeypatch)
    release, calls = threading.Event(), []
    blocking_git(monkeypatch, release, calls)
    monkeypatch.setattr(code_module, "FIRST_FETCH_WAIT_S", 0.5)
    import llmgrader.coursemcp.server as server_module
    monkeypatch.setattr(server_module, "FIRST_FETCH_WAIT_S", 0.5)
    client = app.test_client()
    result = within(10, lambda: call_tool(client, "list_demos", {"course_id": "alpha"}))
    assert "being fetched for the first time" in error_text(result)
    release.set()
    library(app).sync_for("alpha")._thread.join(30)
    assert tool_items(call_tool(client, "list_demos", {"course_id": "alpha"}))


def test_a_hung_sync_never_holds_a_tool_call(client, monkeypatch) -> None:
    """The regression test for "nothing a student waits on touches GitHub"."""
    app = client.application
    search(client, "s_axilite")                         # a copy is in hand
    sync = library(app).sync_for("alpha")
    release, calls = threading.Event(), []
    blocking_git(monkeypatch, release, calls)
    state = sync.state()
    state["synced_at"] = state["last_attempt"] = time.time() - 10_000   # stale
    sync._write_state(state)
    try:
        for name, args in [("search_demos", {"query": "always_ff"}),
                           ("list_demos", {}),
                           ("get_demo_file", {"path": "demos/fsm/counter.sv"}),
                           ("list_demo_files", {"demo": "fsm"})]:
            result = within(2, lambda: call_tool(client, name, {"course_id": "alpha", **args}))
            assert not result.get("isError"), result
        # A refresh did start, off the request path, and is stuck on the network.
        deadline = time.monotonic() + 10
        while "ls-remote" not in calls and time.monotonic() < deadline:
            time.sleep(0.05)
        assert "ls-remote" in calls and sync._thread.is_alive()
    finally:
        release.set()
        if sync._thread:
            sync._thread.join(30)


def test_a_new_commit_is_served_after_the_ttl(app, client, tmp_path) -> None:
    search(client, "s_axilite")
    sync = library(app).sync_for("alpha")
    old = sync.snapshot.commit
    repo = tmp_path / "hwdesign"
    (repo / "demos/fsm/counter.sv").write_text("module counter;\n  // NEW_MARKER\nendmodule\n",
                                               encoding="utf-8")
    new = commit_all(repo)
    assert search(client, "NEW_MARKER")["hits"] == []   # within the TTL: the old copy
    state = sync.state()
    state["synced_at"] = state["last_attempt"] = time.time() - 10_000
    sync._write_state(state)
    search(client, "NEW_MARKER")                        # answered from the old copy...
    sync._thread.join(30)
    assert sync.snapshot.commit == new != old           # ...and the next sees the new one
    assert search(client, "NEW_MARKER")["hits_shown"] == 1


def test_a_failed_sync_keeps_serving_and_a_restart_loads_from_disk(app, client, tmp_path,
                                                                   monkeypatch) -> None:
    search(client, "s_axilite")
    sync = library(app).sync_for("alpha")
    good = sync.snapshot.commit
    monkeypatch.setattr(code_module, "remote_url", lambda config: (tmp_path / "gone").as_uri())
    assert sync.sync_now() is False
    assert sync.snapshot.commit == good
    assert sync.state()["last_error"]
    assert search(client, "s_axilite")["hits_shown"] >= 1
    # A restarted process: no network, the copy on disk.
    fresh = code_module.CodeSync("alpha", sync.config, sync.dir, ttl=10_000)
    calls = []
    real = code_module.run_git
    monkeypatch.setattr(code_module, "run_git", lambda args, **kw: calls.append(args[0]) or real(args, **kw))
    assert fresh.ensure().commit == good
    assert calls == ["rev-parse"]


def test_a_commit_with_a_broken_overrides_file_is_not_served(app, client, tmp_path) -> None:
    search(client, "s_axilite")
    sync = library(app).sync_for("alpha")
    good = sync.snapshot.commit
    repo = tmp_path / "hwdesign"
    (repo / "demos/demos.xml").write_text("<demos><demo id='fsm'><bogus/></demo></demos>",
                                          encoding="utf-8")
    commit_all(repo)
    assert sync.sync_now() is False
    assert sync.snapshot.commit == good
    assert "demos.xml" in sync.state()["last_error"]


def test_a_corrupt_mirror_is_cloned_again(app, client) -> None:
    search(client, "s_axilite")
    sync = library(app).sync_for("alpha")
    good = sync.snapshot.commit
    (sync.mirror / ".git" / "HEAD").unlink()
    assert sync.sync_now() is True
    assert sync.snapshot.commit == good
    assert (sync.mirror / ".git" / "HEAD").is_file()
    assert not (sync.dir / "mirror.new").exists() and not (sync.dir / "mirror.old").exists()


def test_concurrent_refreshes_run_one_sync(app, client, monkeypatch) -> None:
    search(client, "s_axilite")
    sync = library(app).sync_for("alpha")
    release, calls = threading.Event(), []
    blocking_git(monkeypatch, release, calls)
    started = [sync.refresh_in_background() for _ in range(5)]
    release.set()
    sync._thread.join(30)
    assert started.count(True) == 1
    assert calls.count("ls-remote") == 1


def test_a_forked_process_gets_its_own_syncs(app, client, monkeypatch) -> None:
    search(client, "s_axilite")
    lib = library(app)
    first = lib.sync_for("alpha")
    real_pid = os.getpid()
    monkeypatch.setattr(os, "getpid", lambda: real_pid + 1)
    assert lib.sync_for("alpha") is not first
