"""Demo code and docs for the course MCP: ``plans/demo_code_mcp.md``.

A course's ``llmgrader_mcp_config.xml`` may name a public GitHub repo and the
subtrees of it to publish (``<code>``).  The portal keeps a copy of those
subtrees and serves them to the demo tools.  Nothing is packaged: only the
pointer travels in the course package, so a demo fix reaches students without
a rebuild.

Two layers:

* **A mirror on disk**, ``<storage>/courses/<course_id>/code/mirror``: a
  shallow, sparse, partial git clone of the ``<include>`` paths, in the
  repo's own layout.  Bitstreams are never fetched.
* **A snapshot in memory**, :class:`CodeSnapshot`: every servable file's
  text, built from the mirror after each sync and never changed afterwards.
  Tools read only the snapshot, so no reader can see a half-updated tree and
  readers take no lock; a sync swaps in a new snapshot with one assignment.

**Nothing a student waits on touches GitHub** (the 2026-10-06 lesson: one
sync worker, so a request that waits freezes the portal).  A stale copy is
refreshed on a background thread while the call is answered from the copy in
hand; only the very first fetch, with no copy at all, is waited on, and only
for :data:`FIRST_FETCH_WAIT_S`.  A failed sync keeps serving the last good
copy.  Threads are started lazily, in the process that serves the request,
for the reason ``mount.py`` gives.
"""

from __future__ import annotations

import fnmatch
import json
import os
import posixpath
import re
import shutil
import stat
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

CODE_EXTENSIONS = {
    ".sv": "systemverilog", ".svh": "systemverilog",
    ".v": "verilog", ".vh": "verilog",
    ".vhd": "vhdl", ".vhdl": "vhdl",
    ".cpp": "cpp", ".cc": "cpp", ".c": "cpp", ".h": "cpp", ".hpp": "cpp",
    ".py": "python",
    ".tcl": "tcl",
    ".ipynb": "notebook",
    ".md": "markdown",
    ".txt": "text", ".template": "text",
    ".xdc": "constraints",
    ".mk": "make",
}
CODE_FILENAMES = {"Makefile": "make", "makefile": "make"}

# A path with any of these components is build output, whatever its extension.
BUILD_DIRS = {"hls_component", ".Xil", "__pycache__", "logs", "results",
              ".ipynb_checkpoints", ".git"}
BUILD_DIR_GLOBS = ("*_proj", "*.runs", "*.gen", "*.sim", "*.cache", "_build*")

# Vivado writes Tcl that is a record of a run, not something anyone wrote.
GENERATED_TCL_MARKERS = ("Generated by Vivado", "namespace eval ::optrace")

MAX_FILE_BYTES = 256 * 1024
MAX_READ_LINES = 400
MAX_HITS = 25
MAX_HITS_PER_FILE = 4
CONTEXT_LINES = 2
MERGE_GAP = 3            # matches this close together become one hit
MAX_BLOCK_SPAN = 12      # ...unless the hit would grow longer than this
MAX_CONTEXT_CHARS = 200

DEFAULT_TTL_S = 600
GIT_TIMEOUT_S = 60
FIRST_FETCH_WAIT_S = 5.0
DEFAULT_LINKS_FILE = "demos/demos.xml"


class CodeError(Exception):
    """A problem with a request, worded for the model that made it."""


class GitError(Exception):
    """A git command failed or timed out."""


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Include:
    path: str
    kind: str = "code"   # "code" or "doc"


@dataclass(frozen=True)
class CodeConfig:
    """``<code>`` from llmgrader_mcp_config.xml, as the package manifest carries it."""

    repo: str                     # https://github.com/<owner>/<repo>
    branch: str = "main"
    includes: tuple[Include, ...] = ()
    excludes: tuple[str, ...] = ()
    site: str | None = None       # published docs address; else from _config.yml
    links: str | None = None      # the overrides file; default DEFAULT_LINKS_FILE

    @classmethod
    def from_dict(cls, data: dict) -> "CodeConfig":
        return cls(
            repo=str(data["repo"]).rstrip("/").removesuffix(".git"),
            branch=data.get("branch") or "main",
            includes=tuple(Include(i["path"].strip("/"), i.get("kind") or "code")
                           for i in data.get("includes", [])),
            excludes=tuple(data.get("excludes", [])),
            site=(data.get("site") or "").rstrip("/") or None,
            links=data.get("links") or None,
        )

    def to_dict(self) -> dict:
        return {"repo": self.repo, "branch": self.branch,
                "includes": [{"path": i.path, "kind": i.kind} for i in self.includes],
                "excludes": list(self.excludes), "site": self.site, "links": self.links}

    @property
    def owner_repo(self) -> str:
        return self.repo.split("github.com/", 1)[-1]

    @property
    def repo_name(self) -> str:
        return self.owner_repo.rsplit("/", 1)[-1]

    @property
    def links_path(self) -> str:
        return self.links or DEFAULT_LINKS_FILE

    def roots(self, kind: str | None = None) -> list[str]:
        return [i.path for i in self.includes if kind is None or i.kind == kind]

    def kind_of(self, path: str) -> str | None:
        """The kind of the include *path* falls under, or None if outside them all."""
        for include in self.includes:
            if path == include.path or path.startswith(include.path + "/"):
                return include.kind
        return None

    def sparse_patterns(self) -> list[str]:
        """What the mirror checks out: the includes, the overrides file and
        ``_config.yml``, never a bitstream or a docs image."""
        patterns = [f"/{i.path}/" for i in self.includes]
        patterns.append(f"/{self.links_path}")
        if not self.site:
            patterns.append("/_config.yml")
        patterns += ["!*.bit", "!*.hwh", "!*.xsa", "!*.xclbin"]
        for root in self.roots("doc"):
            patterns += [f"!/{root}/**/*.{ext}" for ext in ("png", "jpg", "jpeg", "gif", "svg")]
        return patterns


def remote_url(config: CodeConfig) -> str:
    """Where the mirror is cloned from.  A function so tests can point it at
    a local repository instead of GitHub."""
    return config.repo + ".git"


# ---------------------------------------------------------------------------
# What is served
# ---------------------------------------------------------------------------


def is_build_output(path: str) -> bool:
    parts = path.split("/")[:-1]
    return any(part in BUILD_DIRS or any(fnmatch.fnmatchcase(part, g) for g in BUILD_DIR_GLOBS)
               for part in parts)


def _excluded_by_config(path: str, excludes: tuple[str, ...]) -> bool:
    name = posixpath.basename(path)
    for pattern in excludes:
        target = path if "/" in pattern else name
        if fnmatch.fnmatchcase(target, pattern):
            return True
    return False


def language_of(path: str, text: str = "") -> str | None:
    name = posixpath.basename(path)
    language = CODE_FILENAMES.get(name) or CODE_EXTENSIONS.get(posixpath.splitext(name)[1].lower())
    if language == "cpp" and "#pragma HLS" in text:
        return "hls-cpp"
    return language


def flatten_notebook(raw: str) -> str | None:
    """A notebook as text: each cell's source under a marker line, outputs dropped."""
    try:
        notebook = json.loads(raw)
    except ValueError:
        return None
    lines = []
    for number, cell in enumerate(notebook.get("cells", []), start=1):
        source = cell.get("source", "")
        if isinstance(source, list):
            source = "".join(source)
        lines.append(f"# ---- cell {number} [{cell.get('cell_type', 'code')}] ----")
        lines.extend(source.splitlines())
        lines.append("")
    return "\n".join(lines)


_FRONT_MATTER_KEY = re.compile(r"^([A-Za-z_][\w-]*)\s*:\s*(.*?)\s*$")


def split_front_matter(lines: list[str]) -> tuple[dict, int]:
    """``(front matter, index of the first body line)`` of a Markdown page.

    Only flat ``key: value`` lines are read -- title, parent, nav_order are
    all that is used -- so no YAML library is needed.
    """
    if not lines or lines[0].strip() != "---":
        return {}, 0
    for end in range(1, len(lines)):
        if lines[end].strip() == "---":
            meta = {}
            for line in lines[1:end]:
                match = _FRONT_MATTER_KEY.match(line)
                if match:
                    meta[match.group(1)] = match.group(2).strip().strip("'\"")
            return meta, end + 1
    return {}, 0


_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_MD_LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")


def heading_anchor(text: str) -> str:
    """The id kramdown gives a heading: GitHub Pages' default for just-the-docs."""
    text = _MD_LINK.sub(r"\1", text)
    text = re.sub(r"[^\w\- ]|_", "", text).lower().replace(" ", "-")
    return re.sub(r"^[^a-z]+", "", text)


def _headings(lines: tuple[str, ...]) -> tuple:
    """For each line, the nearest Markdown heading at or above it: ``(text, anchor)``."""
    current = None
    in_fence = False
    result = []
    for line in lines:
        if line.lstrip().startswith(("```", "~~~")):
            in_fence = not in_fence
        elif not in_fence:
            match = _HEADING.match(line)
            if match:
                text = _MD_LINK.sub(r"\1", match.group(2)).replace("`", "").strip()
                current = (text, heading_anchor(match.group(2)))
        result.append(current)
    return tuple(result)


def _normalize(line: str) -> str:
    return " ".join(line.split()).lower()


@dataclass
class SourceFile:
    """One servable file.  *lines* are the served lines; the first of them is
    line *first_line* of the file on GitHub (docs drop their front matter)."""

    path: str
    kind: str                 # "code" or "doc"
    language: str
    lines: tuple[str, ...]
    first_line: int = 1
    meta: dict = field(default_factory=dict)
    norm: tuple[str, ...] = ()
    headings: tuple | None = None

    @property
    def last_line(self) -> int:
        return self.first_line + len(self.lines) - 1

    @property
    def title(self) -> str:
        if self.meta.get("title"):
            return self.meta["title"]
        for line in self.lines:
            match = _HEADING.match(line)
            if match:
                return _MD_LINK.sub(r"\1", match.group(2)).replace("`", "").strip()
        return posixpath.basename(self.path)

    def first_paragraph(self, limit: int = 400) -> str:
        """The first prose paragraph: what a docs page or README says it is."""
        paragraph: list[str] = []
        in_fence = False
        for line in self.lines:
            stripped = line.strip()
            if stripped.startswith(("```", "~~~")):
                in_fence = not in_fence
                if paragraph:
                    break
                continue
            if in_fence:
                continue
            if not stripped or stripped.startswith(("#", "|", "---", "{:", "<", "!")):
                if paragraph:
                    break
                continue
            paragraph.append(stripped)
        text = " ".join(paragraph)
        return text[:limit] + ("…" if len(text) > limit else "")


def _make_source(path: str, kind: str, text: str) -> SourceFile | None:
    language = language_of(path, text)
    if language is None:
        return None
    raw_lines = text.splitlines()
    meta, start = ({}, 0)
    if language == "markdown":
        meta, start = split_front_matter(raw_lines)
    lines = tuple(raw_lines[start:])
    return SourceFile(
        path=path, kind=kind, language=language, lines=lines, first_line=start + 1,
        meta=meta, norm=tuple(_normalize(line) for line in lines),
        headings=_headings(lines) if language == "markdown" else None,
    )


def read_servable(full: Path, path: str, kind: str, excludes: tuple[str, ...]) -> SourceFile | None:
    """*full* as a :class:`SourceFile`, or None if it is not to be served."""
    if is_build_output(path) or _excluded_by_config(path, excludes):
        return None
    if kind == "doc" and not path.lower().endswith(".md"):
        return None
    if language_of(path) is None:
        return None
    try:
        if full.is_symlink() or not full.is_file():
            return None
        data = full.read_bytes()
    except OSError:
        return None
    if b"\0" in data[:8192]:
        return None
    try:
        text = data.decode("utf-8-sig")
    except UnicodeDecodeError:
        return None
    if path.endswith(".ipynb"):
        text = flatten_notebook(text)
        if text is None:
            return None
    if len(text.encode("utf-8")) > MAX_FILE_BYTES:
        return None
    if path.endswith(".tcl"):
        head = "\n".join(text.splitlines()[:10])
        if any(marker in head for marker in GENERATED_TCL_MARKERS):
            return None
    return _make_source(path, kind, text)


# ---------------------------------------------------------------------------
# The snapshot
# ---------------------------------------------------------------------------


_DRIVE = re.compile(r"^[A-Za-z]:")
_SITE_KEY = re.compile(r"^(url|baseurl)\s*:\s*['\"]?([^'\"#\s]*)['\"]?", re.MULTILINE)


def site_from_jekyll(text: str) -> str | None:
    """``url`` + ``baseurl`` from a Jekyll ``_config.yml``."""
    values = {m.group(1): m.group(2) for m in _SITE_KEY.finditer(text)}
    if not values.get("url"):
        return None
    return (values["url"].rstrip("/") + "/" + values.get("baseurl", "").strip("/")).rstrip("/")


class CodeSnapshot:
    """Every servable file of one commit, in memory.  Never changed once built."""

    def __init__(self, commit: str, config: CodeConfig, files: dict[str, SourceFile],
                 tree_files: frozenset[str], tree_dirs: frozenset[str],
                 site: str | None, overrides_text: str | None):
        self.commit = commit
        self.config = config
        self.files = files
        self.tree_files = tree_files     # every file checked out, served or not
        self.tree_dirs = tree_dirs
        self.site = site
        self.overrides_text = overrides_text
        dirs = set()
        for path in files:
            parent = posixpath.dirname(path)
            while parent:
                dirs.add(parent)
                parent = posixpath.dirname(parent)
        self.served_dirs = frozenset(dirs)

    @property
    def short_commit(self) -> str:
        return self.commit[:12]

    # -- links ---------------------------------------------------------------

    def source_url(self, path: str, start: int | None = None, end: int | None = None,
                   *, directory: bool = False) -> str:
        kind = "tree" if directory else "blob"
        url = f"{self.config.repo}/{kind}/{self.commit}/{path}"
        source = self.files.get(path)
        if source is not None and source.language == "notebook":
            return url    # GitHub renders notebooks: no line anchors
        if source is not None and source.language == "markdown":
            url += "?plain=1"
        if start is not None:
            url += f"#L{start}" + (f"-L{end}" if end is not None and end != start else "")
        return url

    def view_url(self, path: str, anchor: str | None = None) -> str | None:
        """The published page for a docs file, or None if there is no site."""
        if not self.site or not path.endswith(".md"):
            return None
        page = path[:-3]
        if posixpath.basename(page) == "index":
            page = posixpath.dirname(page) + "/"
        return f"{self.site}/{page}" + (f"#{anchor}" if anchor else "")

    def links_for(self, path: str, start: int | None = None, end: int | None = None,
                  anchor: str | None = None) -> dict:
        links = {"source_url": self.source_url(path, start, end)}
        view = self.view_url(path, anchor)
        if view:
            links = {"view_url": view, **links}
        return links

    # -- paths ---------------------------------------------------------------

    def normalize_path(self, path: str) -> str:
        """A requested path as a repo path, or a CodeError.

        Never touches the filesystem: the result is only ever looked up in
        :attr:`files`, so a path that escapes the includes simply is not there.
        """
        raw = (path or "").strip().replace("\\", "/")
        if not raw:
            raise CodeError("path is empty; take one from list_demo_files or search_demos.")
        if raw.startswith("/") or _DRIVE.match(raw):
            raise CodeError(f"{path!r} is an absolute path; paths are relative to the "
                            "repository, e.g. 'demos/fsm/counter.sv'.")
        parts = [p for p in raw.split("/") if p not in ("", ".")]
        if ".." in parts:
            raise CodeError(f"{path!r} contains '..'; use a path exactly as "
                            "list_demo_files or search_demos gave it.")
        if len(parts) > 1 and parts[0] == self.config.repo_name and "/".join(parts) not in self.files:
            parts = parts[1:]     # the docs write paths as hwdesign/demos/...
        return "/".join(parts)

    def get(self, path: str) -> SourceFile:
        normalized = self.normalize_path(path)
        found = self.files.get(normalized)
        if found is not None:
            return found
        if normalized in self.tree_files or (normalized in self.tree_dirs
                                             and normalized not in self.served_dirs):
            raise CodeError(f"{normalized!r} is not served: build output, binaries, "
                            "bitstreams and generated files are left out.")
        if normalized in self.served_dirs:
            raise CodeError(f"{normalized!r} is a directory; list_demo_files lists the files "
                            "of a demo.")
        raise CodeError(f"No file {normalized!r}. Take paths from list_demo_files or "
                        "search_demos.")

    # -- reading -------------------------------------------------------------

    def read(self, path: str, start_line: int | None = None, end_line: int | None = None) -> dict:
        source = self.get(path)
        first, last = source.first_line, source.last_line
        if not source.lines:
            raise CodeError(f"{source.path!r} is empty.")
        start = max(first, start_line or first)
        if start > last:
            raise CodeError(f"{source.path!r} has lines {first} to {last}.")
        end = min(last, end_line if end_line is not None else last)
        if end < first:
            raise CodeError(f"Lines 1 to {first - 1} of {source.path!r} are its front matter; "
                            f"its text is lines {first} to {last}.")
        if end < start:
            raise CodeError(f"end_line {end_line} is before start_line {start}.")
        end = min(end, start + MAX_READ_LINES - 1)
        width = len(str(end))
        text = "\n".join(f"{n:>{width}}  {source.lines[n - first]}" for n in range(start, end + 1))
        result = {"path": source.path, "kind": source.kind, "language": source.language,
                  "lines": last}
        if first > 1:
            result["first_line"] = first   # a docs page's front matter is not served
        result.update({
            "start_line": start, "end_line": end,
            "truncated": end < min(last, end_line if end_line is not None else last),
            "text": text,
        })
        if source.kind == "doc":
            result["title"] = source.title
        result.update(self.links_for(source.path, start, end))
        return result

    # -- searching -----------------------------------------------------------

    def search(self, query: str, *, paths=None, kind: str | None = None,
               demos_for=lambda path: []) -> dict:
        """Case-insensitive literal search; adjacent matches merge into one hit."""
        needle = _normalize(query or "")
        if not needle:
            raise CodeError("query is empty.")
        blocks = []
        for source in self.files.values():
            if paths is not None and source.path not in paths:
                continue
            if kind and source.kind != kind:
                continue
            matches = [i for i, line in enumerate(source.norm) if needle in line]
            if matches:
                blocks.extend((source, block) for block in _merge(matches))
        blocks.sort(key=lambda b: (_rank(b[0]), b[0].path, b[1][0]))
        hits, per_file = [], {}
        for source, block in blocks:
            if len(hits) >= MAX_HITS or per_file.get(source.path, 0) >= MAX_HITS_PER_FILE:
                continue
            per_file[source.path] = per_file.get(source.path, 0) + 1
            hits.append(self._hit(source, block, demos_for))
        return {
            "matched_lines": sum(len(b[1]) for b in blocks),
            "hits_shown": len(hits),
            "more": len(blocks) - len(hits),
            "hits": hits,
        }

    def _hit(self, source: SourceFile, block: list[int], demos_for) -> dict:
        first_i, last_i = block[0], block[-1]
        lo = max(0, first_i - CONTEXT_LINES)
        hi = min(len(source.lines) - 1, last_i + CONTEXT_LINES)
        width = len(str(source.first_line + hi))
        matched = set(block)
        context = "\n".join(
            f"{'>' if i in matched else ' '} {source.first_line + i:>{width}}  "
            f"{_clip(source.lines[i])}"
            for i in range(lo, hi + 1)
        )
        start, end = source.first_line + first_i, source.first_line + last_i
        hit = {"path": source.path, "kind": source.kind, "demos": demos_for(source.path)}
        anchor = None
        if source.kind == "doc":
            hit["title"] = source.title
            heading = source.headings[first_i] if source.headings else None
            if heading:
                hit["heading"] = heading[0]
                anchor = heading[1] or None
        else:
            hit["language"] = source.language
        hit.update({"start_line": start, "end_line": end, "context": context})
        hit.update(self.links_for(source.path, start, end, anchor))
        return hit


def _clip(line: str) -> str:
    return line if len(line) <= MAX_CONTEXT_CHARS else line[:MAX_CONTEXT_CHARS] + "…"


def _merge(matches: list[int]) -> list[list[int]]:
    blocks = [[matches[0]]]
    for i in matches[1:]:
        if i - blocks[-1][-1] <= MERGE_GAP and i - blocks[-1][0] < MAX_BLOCK_SPAN:
            blocks[-1].append(i)
        else:
            blocks.append([i])
    return blocks


_LANGUAGE_RANK = {"systemverilog": 1, "verilog": 1, "vhdl": 1, "hls-cpp": 1, "cpp": 1,
                  "tcl": 1, "constraints": 1, "python": 2, "make": 2, "notebook": 3}


def _rank(source: SourceFile) -> int:
    """Docs explain, so they come first; then hand-written source, scripts, notebooks."""
    if source.kind == "doc":
        return 0
    return _LANGUAGE_RANK.get(source.language, 4)


def build_snapshot(tree_root: str | Path, config: CodeConfig, commit: str,
                   *, only: set[str] | None = None) -> CodeSnapshot:
    """Read every servable file under *config*'s includes in *tree_root*.

    *only*, when given, limits the walk to those repo paths -- the build uses
    it with ``git ls-files`` so an instructor's untracked build output never
    shows up in the report.  Symlinks are never followed.
    """
    tree_root = Path(tree_root)
    files: dict[str, SourceFile] = {}
    tree_files: set[str] = set()
    tree_dirs: set[str] = set()
    for include in config.includes:
        base = tree_root / include.path
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base, followlinks=False):
            rel_dir = Path(dirpath).relative_to(tree_root).as_posix()
            dirnames[:] = [d for d in dirnames if d != ".git"]
            tree_dirs.add(rel_dir)
            for name in filenames:
                path = f"{rel_dir}/{name}"
                if only is not None and path not in only:
                    continue
                tree_files.add(path)
                source = read_servable(Path(dirpath) / name, path, include.kind, config.excludes)
                if source is not None:
                    files[path] = source
    site = config.site
    if not site:
        try:
            site = site_from_jekyll((tree_root / "_config.yml").read_text(encoding="utf-8"))
        except OSError:
            site = None
    try:
        overrides = (tree_root / config.links_path).read_text(encoding="utf-8")
    except OSError:
        overrides = None
    return CodeSnapshot(commit, config, dict(sorted(files.items())), frozenset(tree_files),
                        frozenset(tree_dirs), site, overrides)


# ---------------------------------------------------------------------------
# Sync
# ---------------------------------------------------------------------------


def run_git(args: list[str], *, cwd: str | Path | None = None,
            timeout: float = GIT_TIMEOUT_S) -> str:
    """Run one git command; its stdout, or a GitError.

    Never prompts: a repo that has gone private must fail now, not wait for
    a password nobody will type, and no credential helper may open a window.
    """
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0", GCM_INTERACTIVE="never")
    try:
        result = subprocess.run(
            ["git", "-c", "credential.helper=", "-c", "core.askPass=", *args],
            cwd=cwd, env=env, capture_output=True, text=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        raise GitError(f"git {args[0]} timed out after {timeout:.0f}s") from exc
    except OSError as exc:
        raise GitError(f"git could not run: {exc}") from exc
    if result.returncode != 0:
        raise GitError(f"git {args[0]} failed: {(result.stderr or result.stdout).strip()[:300]}")
    return result.stdout


def _rmtree(path: Path) -> None:
    """``shutil.rmtree`` that also removes git's read-only pack files on Windows."""
    def make_writable(func, target, _exc):
        try:
            os.chmod(target, stat.S_IWRITE)
            func(target)
        except OSError:
            pass
    if path.exists():
        shutil.rmtree(path, onerror=make_writable)


class _FileLock:
    """An flock on *path*, across gunicorn workers.  A no-op on Windows, where
    the dev server is a single process."""

    def __init__(self, path: Path, *, exclusive: bool):
        self.path, self.exclusive = path, exclusive
        self.handle = None
        self.acquired = False

    def __enter__(self) -> bool:
        try:
            import fcntl
        except ImportError:
            self.acquired = True
            return True
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.handle = open(self.path, "a+")
        mode = (fcntl.LOCK_EX if self.exclusive else fcntl.LOCK_SH) | fcntl.LOCK_NB
        try:
            fcntl.flock(self.handle, mode)
            self.acquired = True
        except OSError:
            self.acquired = False
        return self.acquired

    def __exit__(self, *exc) -> None:
        if self.handle is not None:
            if self.acquired:
                import fcntl
                fcntl.flock(self.handle, fcntl.LOCK_UN)
            self.handle.close()


class SnapshotRejected(Exception):
    """A new commit that must not replace the copy being served."""


def validate_snapshot(snapshot: CodeSnapshot) -> None:
    """Refuse a commit that would empty the tools or has a broken overrides file."""
    if not snapshot.files:
        raise SnapshotRejected("no servable files under the <include> paths")
    from llmgrader.coursemcp.demo_links import OverridesError, parse_overrides

    try:
        parse_overrides(snapshot.overrides_text)
    except OverridesError as exc:
        raise SnapshotRejected(f"{snapshot.config.links_path}: {exc}") from exc


class CodeSync:
    """One course's copy of its demo repo: the mirror, the snapshot, the syncing."""

    def __init__(self, course_id: str, config: CodeConfig, directory: str | Path,
                 *, ttl: float | None = None):
        self.course_id = course_id
        self.config = config
        self.dir = Path(directory)
        self.mirror = self.dir / "mirror"
        self.state_path = self.dir / "state.json"
        self.ttl = ttl if ttl is not None else _ttl_from_env()
        self._snapshot: CodeSnapshot | None = None
        self._sync_lock = threading.Lock()
        self._load_lock = threading.Lock()
        self._thread: threading.Thread | None = None
        self._index_key = None
        self._index = None
        self._index_refs = None     # keeps the keyed objects alive, so ids are not reused

    @property
    def snapshot(self) -> CodeSnapshot | None:
        return self._snapshot

    # -- state.json ----------------------------------------------------------

    def state(self) -> dict:
        try:
            return json.loads(self.state_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return {}

    def _write_state(self, state: dict) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        tmp = self.state_path.with_suffix(".tmp")
        tmp.write_text(json.dumps(state, indent=1), encoding="utf-8")
        tmp.replace(self.state_path)

    def _stale(self, state: dict) -> bool:
        last = max(state.get("synced_at") or 0, state.get("last_attempt") or 0)
        return time.time() - last >= self.ttl

    # -- serving -------------------------------------------------------------

    def ensure(self, *, wait: float = 0.0) -> CodeSnapshot | None:
        """The snapshot to serve, starting a background refresh if it is stale.

        Waits (up to *wait* seconds) only when there is no copy at all.
        """
        if self._snapshot is None:
            self._load_from_disk()
        state = self.state()
        if (self._snapshot is not None and state.get("commit")
                and state["commit"] != self._snapshot.commit):
            self._load_from_disk()    # another worker synced
        if self._snapshot is None or self._stale(state):
            self.refresh_in_background()
        if self._snapshot is None and wait > 0:
            thread = self._thread
            if thread is not None:
                thread.join(wait)
        return self._snapshot

    def last_error(self) -> str | None:
        return self.state().get("last_error")

    def index(self, snapshot: CodeSnapshot, materials):
        """The demo link graph for *snapshot* and the course's slides, cached."""
        from llmgrader.coursemcp.demo_links import build_index, slides_from_materials

        key = (id(snapshot), id(materials))
        if self._index_key != key or self._index is None:
            index = build_index(snapshot, slides_from_materials(materials))
            self._index, self._index_key = index, key
            self._index_refs = (snapshot, materials)
        return self._index

    def _load_from_disk(self) -> None:
        with self._load_lock:
            if not (self.mirror / ".git").is_dir():
                return
            with _FileLock(self.dir / ".lock", exclusive=False) as got:
                if not got:
                    return      # a sync is mid-way in another worker; try later
                try:
                    commit = run_git(["rev-parse", "HEAD"], cwd=self.mirror, timeout=15).strip()
                    if self._snapshot is not None and self._snapshot.commit == commit:
                        return
                    snapshot = build_snapshot(self.mirror, self.config, commit)
                    validate_snapshot(snapshot)
                except (GitError, SnapshotRejected, OSError) as exc:
                    print(f"[CourseCode] {self.course_id}: copy on disk not loaded: {exc}")
                    return
                self._snapshot = snapshot

    # -- syncing -------------------------------------------------------------

    def refresh_in_background(self) -> bool:
        """Start a sync on a thread unless one is running; True if started."""
        if not self._sync_lock.acquire(blocking=False):
            return False

        def run():
            try:
                self._sync()
            except Exception as exc:  # a thread must never die loudly mid-request
                print(f"[CourseCode] {self.course_id}: sync crashed: {exc!r}")
            finally:
                self._sync_lock.release()

        try:
            thread = threading.Thread(target=run, daemon=True,
                                      name=f"course-code-sync-{self.course_id}")
            self._thread = thread
            thread.start()
        except Exception:
            self._sync_lock.release()
            raise
        return True

    def sync_now(self) -> bool:
        """Sync in this thread (tests, tools).  True if the copy is current."""
        with self._sync_lock:
            return self._sync()

    def _sync(self) -> bool:
        with _FileLock(self.dir / ".lock", exclusive=True) as got:
            if not got:
                return False
            state = self.state()
            state["last_attempt"] = time.time()
            ok = False
            try:
                commit = self._fetch(state)
                if self._snapshot is None or self._snapshot.commit != commit:
                    snapshot = build_snapshot(self.mirror, self.config, commit)
                    validate_snapshot(snapshot)
                    self._snapshot = snapshot
                    print(f"[CourseCode] {self.course_id}: serving {commit[:12]} "
                          f"({len(snapshot.files)} files)")
                state.update(commit=commit, synced_at=time.time(), last_error=None)
                ok = True
            except (GitError, SnapshotRejected, OSError) as exc:
                state["last_error"] = str(exc)[:500]
                print(f"[CourseCode] {self.course_id}: sync failed, serving the last good "
                      f"copy: {exc}")
            finally:
                try:
                    self._write_state(state)
                except OSError as exc:
                    print(f"[CourseCode] {self.course_id}: could not write state: {exc}")
            return ok

    def _mirror_head(self) -> str | None:
        if not (self.mirror / ".git").is_dir():
            return None
        try:
            return run_git(["rev-parse", "HEAD"], cwd=self.mirror, timeout=15).strip()
        except GitError:
            return None

    def _fetch(self, state: dict) -> str:
        """Bring the mirror up to the branch head; return the commit it is at."""
        remote = remote_url(self.config)
        patterns = self.config.sparse_patterns()
        head = self._mirror_head()
        if head is None or state.get("remote") != remote:
            self._clone(remote, patterns)
        else:
            listing = run_git(["ls-remote", remote, f"refs/heads/{self.config.branch}"])
            remote_head = listing.split()[0] if listing.strip() else None
            if remote_head is None:
                raise GitError(f"branch {self.config.branch!r} not found in {self.config.repo}")
            if remote_head != head or state.get("patterns") != patterns:
                try:
                    if state.get("patterns") != patterns:
                        run_git(["sparse-checkout", "set", "--no-cone", *patterns], cwd=self.mirror)
                    run_git(["fetch", "--depth", "1", "--filter=blob:none", "origin",
                             self.config.branch], cwd=self.mirror)
                    run_git(["reset", "-q", "--hard", "FETCH_HEAD"], cwd=self.mirror)
                except GitError as exc:
                    print(f"[CourseCode] {self.course_id}: mirror update failed ({exc}); "
                          "cloning afresh")
                    self._clone(remote, patterns)
        state.update(remote=remote, patterns=patterns)
        head = self._mirror_head()
        if head is None:
            raise GitError("the mirror has no commit after syncing")
        return head

    def _clone(self, remote: str, patterns: list[str]) -> None:
        """Clone into ``mirror.new`` and move it into place only once complete."""
        self.dir.mkdir(parents=True, exist_ok=True)
        new, old = self.dir / "mirror.new", self.dir / "mirror.old"
        _rmtree(new)
        run_git(["clone", "-q", "--depth", "1", "--filter=blob:none", "--no-checkout",
                 "--branch", self.config.branch, remote, str(new)])
        run_git(["sparse-checkout", "set", "--no-cone", *patterns], cwd=new)
        run_git(["reset", "-q", "--hard", "HEAD"], cwd=new)
        _rmtree(old)
        if self.mirror.exists():
            self.mirror.rename(old)
        new.rename(self.mirror)
        _rmtree(old)


def _ttl_from_env() -> float:
    try:
        return float(os.environ.get("LLMGRADER_CODE_SYNC_TTL_S", "") or DEFAULT_TTL_S)
    except ValueError:
        return DEFAULT_TTL_S


class CodeLibrary:
    """One :class:`CodeSync` per course that publishes demos, per process.

    Rebuilt after a fork, like ``CourseMCPRunner``: a lock copied from the
    parent mid-sync would stay held forever in the child.
    """

    def __init__(self, registry, *, ttl: float | None = None):
        self.registry = registry
        self.ttl = ttl
        self._lock = threading.Lock()
        self._pid = os.getpid()
        self._syncs: dict[str, CodeSync] = {}

    def config_for(self, course_id: str) -> CodeConfig | None:
        from llmgrader.coursemcp.materials import load_materials

        materials = load_materials(self.registry.grader_for(course_id).soln_pkg)
        if materials is None or not materials.code:
            return None
        return CodeConfig.from_dict(materials.code)

    def sync_for(self, course_id: str) -> CodeSync | None:
        config = self.config_for(course_id)
        if config is None:
            return None
        with self._lock:
            if self._pid != os.getpid():
                self._syncs, self._pid = {}, os.getpid()
            existing = self._syncs.get(course_id)
            if existing is not None and existing.config == config:
                return existing
            sync = CodeSync(course_id, config,
                            Path(self.registry.course_dir(course_id)) / "code", ttl=self.ttl)
            self._syncs[course_id] = sync
            return sync

    def warm(self) -> None:
        """Load or refresh every course's copy, without waiting on any of it."""
        for entry in self.registry.courses():
            try:
                sync = self.sync_for(entry.id)
                if sync is not None:
                    sync.ensure(wait=0)
            except Exception as exc:
                print(f"[CourseCode] {entry.id}: {exc!r}")

    def code_version(self, course_id) -> str | None:
        """The commit being served for *course_id*, if any.  Never syncs."""
        if not isinstance(course_id, str):
            return None
        sync = self._syncs.get(course_id)
        snapshot = sync.snapshot if sync is not None else None
        return snapshot.short_commit if snapshot is not None else None
